"""
Detailed report for Reiha - Service Account Analysis
"""
import json
from pathlib import Path
from datetime import datetime

creds_file = Path('config/aim-tashiro-poc-09a7f137eb05.json')

print('=' * 70)
print('DETAILED REPORT FOR REIHA')
print('=' * 70)

# Load credentials
with open(creds_file, 'r') as f:
    creds = json.load(f)

print('\n📋 CONNECTION METHOD:')
print('-' * 70)
print('✔ We are using: SERVICE ACCOUNT (not direct API connection)')
print('✔ Authentication: OAuth 2.0 with service account key file')
print('✔ Method: Application Default Credentials (ADC)')

print('\n📋 SERVICE ACCOUNT DETAILS:')
print('-' * 70)
print(f'Type: {creds.get("type")}')
print(f'Project ID: {creds.get("project_id")}')
print(f'Service Account Email: {creds.get("client_email")}')
print(f'Private Key ID: {creds.get("private_key_id")}')
print(f'Client ID: {creds.get("client_id")}')

print('\n📋 AUTHENTICATION ENDPOINTS:')
print('-' * 70)
print(f'Auth URI: {creds.get("auth_uri")}')
print(f'Token URI: {creds.get("token_uri")}')
print(f'Auth Provider Cert URL: {creds.get("auth_provider_x509_cert_url")}')

print('\n📋 FILE INFORMATION:')
print('-' * 70)
print(f'File Path: {creds_file.absolute()}')
print(f'File Size: {creds_file.stat().st_size} bytes')
file_time = datetime.fromtimestamp(creds_file.stat().st_mtime)
print(f'Last Modified: {file_time.strftime("%Y-%m-%d %H:%M:%S")}')

print('\n📋 CURRENT ERROR STATUS:')
print('-' * 70)
print('❌ Error: 401 AUTHENTICATION FAILED')
print('❌ Specific Error: "invalid_scope: Invalid OAuth scope or ID token audience provided"')
print('')
print('What this means:')
print('  - The service account key file EXISTS and is READABLE')
print('  - The project ID and service account email are CORRECT')
print('  - BUT: The OAuth token cannot be generated from this key')
print('  - Reason: The key has invalid OAuth scopes configured')

print('\n📋 ROOT CAUSE:')
print('-' * 70)
print('The service account key file has an OAuth scope configuration problem.')
print('This is NOT an IAM role issue on Google Cloud side.')
print('This is a credential generation/validation issue.')
print('')
print('Possible causes:')
print('  1. The key was created before APIs were properly enabled')
print('  2. The key was created with wrong OAuth scopes')
print('  3. The key is expired or was revoked')
print('  4. The key was created during incomplete API setup')

print('\n📋 APIs BEING ACCESSED:')
print('-' * 70)
print('1. Document AI API')
print('   - Endpoint: documentai.googleapis.com')
print('   - Required Scope: https://www.googleapis.com/auth/cloud-platform')
print('   - Status: ❌ FAILING (401)')
print('')
print('2. Cloud Vision API')
print('   - Endpoint: vision.googleapis.com')
print('   - Required Scope: https://www.googleapis.com/auth/cloud-platform')
print('   - Status: ❌ FAILING (401)')

print('\n📋 WHAT REIHA NEEDS TO CHECK:')
print('-' * 70)
print('')
print('Question 1: Connection Method')
print('Answer: We are using SERVICE ACCOUNT authentication')
print('        (Not direct API key access)')
print('')
print('Question 2: Is error still occurring?')
print('Answer: YES - Both Document AI and Vision API return 401 errors')
print('')
print('Question 3: What is the exact error?')
print('Answer: "invalid_scope: Invalid OAuth scope or ID token audience"')
print('        This means the service account key cannot obtain valid OAuth tokens')

print('\n📋 REQUIRED ACTION FROM GOOGLE CLOUD ADMIN:')
print('-' * 70)
print('')
print('Option 1: REGENERATE SERVICE ACCOUNT KEY (Recommended)')
print('  1. Go to: https://console.cloud.google.com/iam-admin/serviceaccounts')
print('  2. Select project: aim-tashiro-poc')
print('  3. Find service account: aim-vision-api-dev@aim-tashiro-poc.iam.gserviceaccount.com')
print('  4. Click Keys → Add Key → Create new key → JSON')
print('  5. Send the new JSON file to replace current one')
print('  6. Delete old key for security')
print('')
print('Option 2: VERIFY API ENABLEMENT')
print('  1. Check Document AI is enabled: https://console.cloud.google.com/apis/library/documentai.googleapis.com')
print('  2. Check Vision API is enabled: https://console.cloud.google.com/apis/library/vision.googleapis.com')
print('  3. Ensure both APIs were enabled BEFORE the service account key was created')
print('')
print('Option 3: VERIFY IAM ROLES (Less likely to be the issue)')
print('  Ensure service account has these roles:')
print('  - roles/documentai.apiUser')
print('  - roles/cloudvision.user')

print('\n' + '=' * 70)
print('TECHNICAL SUMMARY FOR MIZUKI/REIHA')
print('=' * 70)
print('')
print('Connection Type: Service Account (OAuth 2.0)')
print('Service Account: aim-vision-api-dev@aim-tashiro-poc.iam.gserviceaccount.com')
print('Project: aim-tashiro-poc')
print('Error Code: 401 Unauthorized')
print('Error Type: OAuth scope validation failure')
print('Issue Location: Service account key file')
print('Solution: Regenerate service account key')
print('')
print('=' * 70)
